name: Build AHK v2

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (AHK v2, x64+x86)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with AutoHotkey Build action (v2)
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          # Use an explicit v2 release tag from the official AutoHotkey repo.
          # To always get the latest v2 at build time, set this to the latest v2 tag when you update.
          version: v2.0.18
          x64: true
          x86: true
          x64_suffix: -x64
          x86_suffix: -x86
          compression: upx
          in: .
          out: dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winToMacRustdesk
          path: dist/*.exe
