name: Build AHK v2

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (AHK v2, x64+x86)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with AutoHotkey Build action (v2)
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          # Use an explicit v2 release tag from the official AutoHotkey repo.
          # To always get the latest v2 at build time, set this to the latest v2 tag when you update.
          version: v2.0.18
          x64: true
          x86: true
          x64_suffix: -x64
          x86_suffix: -x86
          compression: upx
          in: .
          out: dist

      - name: Capture release timestamp
        id: release_meta
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
          "release_tag=ahk-build-$timestamp" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "release_name=AutoHotkey Build $timestamp" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winToMacRustdesk
          path: dist/*.exe

      - name: Publish release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_meta.outputs.release_tag }}
          name: ${{ steps.release_meta.outputs.release_name }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            dist/*.exe
